export interface NFT {
  id: string;
  name: string;
  price: number;
  image: string;
  creator: string;
  creatorAddress: string;
  likes: number;
  views: number;
  isLiked: boolean;
  rarity?: string;
  category: string;
  description: string;
  tokenId: string;
  createdAt: string;
}

export const mockNFTs: NFT[] = [
  {
    id: '1',
    name: 'Cosmic Wanderer #001',
    price: 2.5,
    image: 'https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'AstroArtist',
    creatorAddress: '7xKXtg2CW3y...',
    likes: 234,
    views: 1567,
    isLiked: false,
    rarity: 'Rare',
    category: 'art',
    description: 'A mesmerizing journey through the cosmos, featuring vibrant nebulas and distant galaxies. This piece represents the infinite possibilities of space exploration.',
    tokenId: '#001',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Digital Dreams',
    price: 1.8,
    image: 'https://images.pexels.com/photos/1089440/pexels-photo-1089440.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'PixelMaster',
    creatorAddress: '9bYwQr5L8z1...',
    likes: 189,
    views: 892,
    isLiked: true,
    rarity: 'Common',
    category: 'art',
    description: 'An abstract exploration of digital consciousness and virtual reality. The interplay of colors represents the boundary between real and virtual worlds.',
    tokenId: '#002',
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    name: 'Neon Samurai',
    price: 4.2,
    image: 'https://images.pexels.com/photos/1287145/pexels-photo-1287145.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'CyberNinja',
    creatorAddress: '3fHnVi9Km2s...',
    likes: 567,
    views: 2341,
    isLiked: false,
    rarity: 'Epic',
    category: 'collectibles',
    description: 'A futuristic samurai warrior illuminated by neon lights in a cyberpunk cityscape. Honor meets technology in this stunning digital artwork.',
    tokenId: '#003',
    createdAt: '2024-01-08',
  },
  {
    id: '4',
    name: 'Ocean Depths',
    price: 3.1,
    image: 'https://images.pexels.com/photos/1619317/pexels-photo-1619317.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'AquaVision',
    creatorAddress: '8kTpMs3Nv7r...',
    likes: 345,
    views: 1678,
    isLiked: false,
    category: 'photography',
    description: 'Dive into the mysterious depths of the ocean where light dances through the water, revealing hidden treasures and marine life.',
    tokenId: '#004',
    createdAt: '2024-01-05',
  },
  {
    id: '5',
    name: 'Mystic Forest',
    price: 2.7,
    image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'NatureSoul',
    creatorAddress: '5rWnXz8Qp4m...',
    likes: 278,
    views: 1234,
    isLiked: true,
    rarity: 'Uncommon',
    category: 'art',
    description: 'An enchanted forest where magic dwells among ancient trees and mystical creatures. Each shadow tells a story of forgotten legends.',
    tokenId: '#005',
    createdAt: '2024-01-03',
  },
  {
    id: '6',
    name: 'Urban Pulse',
    price: 1.9,
    image: 'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'CityVibes',
    creatorAddress: '6vYqRs1Hl9n...',
    likes: 456,
    views: 2567,
    isLiked: false,
    category: 'photography',
    description: 'The rhythm of city life captured in a single moment. Skyscrapers reach for the sky while the pulse of urban energy flows through the streets.',
    tokenId: '#006',
    createdAt: '2024-01-01',
  },
  {
    id: '7',
    name: 'Dragon\'s Lair',
    price: 5.5,
    image: 'https://images.pexels.com/photos/1271619/pexels-photo-1271619.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'FantasyForge',
    creatorAddress: '4mBnKt7Px3w...',
    likes: 789,
    views: 3456,
    isLiked: true,
    rarity: 'Legendary',
    category: 'gaming',
    description: 'Enter the legendary dragon\'s lair where ancient treasures are guarded by the most powerful creature of myth and legend.',
    tokenId: '#007',
    createdAt: '2023-12-28',
  },
  {
    id: '8',
    name: 'Ethereal Melody',
    price: 3.8,
    image: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'SoundWaves',
    creatorAddress: '2cDrFh6Mn8v...',
    likes: 234,
    views: 1456,
    isLiked: false,
    category: 'music',
    description: 'A visual representation of music itself, where sound waves become art and melodies transform into colors that dance across the canvas.',
    tokenId: '#008',
    createdAt: '2023-12-25',
  },
  {
    id: '9',
    name: 'Quantum Realm',
    price: 4.7,
    image: 'https://images.pexels.com/photos/1205301/pexels-photo-1205301.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'SciArt',
    creatorAddress: '1xGkPz4Lv5t...',
    likes: 567,
    views: 2789,
    isLiked: true,
    rarity: 'Epic',
    category: 'art',
    description: 'Explore the subatomic world where particles exist in multiple states simultaneously. Science meets art in this quantum masterpiece.',
    tokenId: '#009',
    createdAt: '2023-12-20',
  },
  {
    id: '10',
    name: 'Stellar Genesis',
    price: 6.2,
    image: 'https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'CosmicCreator',
    creatorAddress: '9hFnWs2Qr7k...',
    likes: 892,
    views: 4123,
    isLiked: false,
    rarity: 'Legendary',
    category: 'art',
    description: 'Witness the birth of stars in this cosmic masterpiece. The genesis of stellar objects illuminates the darkness of space with brilliant colors.',
    tokenId: '#010',
    createdAt: '2023-12-15',
  },
  {
    id: '11',
    name: 'Retro Wave',
    price: 2.3,
    image: 'https://images.pexels.com/photos/1226302/pexels-photo-1226302.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'VaporArt',
    creatorAddress: '8vCnRt3Mp6j...',
    likes: 345,
    views: 1567,
    isLiked: false,
    category: 'art',
    description: 'Step back into the 80s with this synthwave-inspired artwork featuring neon grids and retro-futuristic aesthetics.',
    tokenId: '#011',
    createdAt: '2023-12-12',
  },
  {
    id: '12',
    name: 'Crystal Cave',
    price: 3.4,
    image: 'https://images.pexels.com/photos/1366957/pexels-photo-1366957.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'GemCrafter',
    creatorAddress: '7nBkYs9Lq2w...',
    likes: 456,
    views: 1890,
    isLiked: true,
    rarity: 'Rare',
    category: 'collectibles',
    description: 'Deep within the earth lies a crystal cave of extraordinary beauty, where gemstones catch and refract light in magical ways.',
    tokenId: '#012',
    createdAt: '2023-12-10',
  },
  {
    id: '13',
    name: 'Mechanical Dreams',
    price: 2.9,
    image: 'https://images.pexels.com/photos/1020315/pexels-photo-1020315.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'SteamPunk',
    creatorAddress: '6jPrVz1Nh4s...',
    likes: 278,
    views: 1234,
    isLiked: false,
    category: 'art',
    description: 'A steampunk-inspired creation where gears, cogs, and mechanical elements come together in perfect harmony to create something beautiful.',
    tokenId: '#013',
    createdAt: '2023-12-08',
  },
  {
    id: '14',
    name: 'Digital Phoenix',
    price: 4.1,
    image: 'https://images.pexels.com/photos/1146134/pexels-photo-1146134.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'MythMaker',
    creatorAddress: '5kTwQs8Mf7r...',
    likes: 623,
    views: 2456,
    isLiked: true,
    rarity: 'Epic',
    category: 'collectibles',
    description: 'Rising from the digital ashes, this phoenix represents rebirth and transformation in the modern age of technology.',
    tokenId: '#014',
    createdAt: '2023-12-05',
  },
  {
    id: '15',
    name: 'Neon Nights',
    price: 1.7,
    image: 'https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'NightVision',
    creatorAddress: '4rFhXp6Lk9m...',
    likes: 234,
    views: 978,
    isLiked: false,
    category: 'photography',
    description: 'The electric energy of the night comes alive in this neon-soaked urban landscape where shadows dance with light.',
    tokenId: '#015',
    createdAt: '2023-12-03',
  },
  {
    id: '16',
    name: 'Abstract Harmony',
    price: 2.6,
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',
    creator: 'AbstractMind',
    creatorAddress: '3dGnVr5Qs8p...',
    likes: 345,
    views: 1456,
    isLiked: false,
    category: 'art',
    description: 'An exploration of color, form, and emotion where abstract elements unite to create a sense of perfect harmony and balance.',
    tokenId: '#016',
    createdAt: '2023-12-01',
  },
];